name: Metrics

on:
  schedule:
    - cron: "30 21 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: aptmara
          filename: github-metrics.svg

          template: classic
          config_timezone: Asia/Tokyo

          # Private / Organization repositories
          repositories_affiliations: owner, collaborator, organization_member
          repositories: 200

          # More accurate base statistics
          base: header, activity, community, repositories, metadata
          base_indepth: yes

          # Full-year contribution calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Languages
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: percentage
          plugin_languages_limit: 8

          # Recent language activity
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 500
