name: validate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  profile:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate profile files
        shell: pwsh
        run: ./tests/validate-profile.ps1
